### ISSUE TITLE
Is “Omniplan logo” een goede alternatieve tekst hier?

### ISSUE THREAD

**Issue by KrijnHoetmer** [luukbrauckmann/sprint-12-leertaak#15]
https://github.com/luukbrauckmann/sprint-12-leertaak/blob/15778c48553bad7f99755975dd3c07090474b90e/src/views/partials/header.ejs#L4

**Comment by slimluccii** [comment]
Ik heb even snel online opgezocht wat een goede alt tekst is voor een logo en ik kwam tegen dat het beste gewoon de naam van het bedrijf als alt tekst kunt hebben. Mits het natuurlijk er naast als tekst staat wat in ons geval niet zo is, dus het is nu gewoon `alt="Omniplan"`
